# Numpy

In [1]:
import numpy as np

In [2]:
array = np.array([7, 5, 3])
print(array)

[7 5 3]


In [3]:
array2 = np.array([0, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])
print(array2.shape)

(15,)


In [7]:
n = array2.reshape(3,5)
print(n)

[[ 0  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]]


In [8]:
print("My Array Shape:", n.shape)

My Array Shape: (3, 5)


In [9]:
print("My Array Dimension:", n.ndim)

My Array Dimension: 2


In [10]:
print("Data Type: ", n.dtype.name)

Data Type:  int32


In [11]:
print("Size Of My Array:", n.size)

Size Of My Array: 15


In [12]:
print("Type Of My Array:", type(n))

Type Of My Array: <class 'numpy.ndarray'>


In [19]:
array3= np.array([["h","e","y","!"],["You","look","gorgeous","today!"]])

In [20]:
print(array3)

[['h' 'e' 'y' '!']
 ['You' 'look' 'gorgeous' 'today!']]


In [21]:
array3.shape

(2, 4)

In [22]:
zeros= np.zeros((2,6))

In [23]:
print(zeros)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [24]:
zeros[0,0]=2
print(zeros)

[[2. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [25]:
ones = np.ones((6,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [26]:
    np.empty((5,6))

array([[1.30321905e-311, 1.02765654e-321, 0.00000000e+000,
        0.00000000e+000, 1.37961302e-306, 5.02034658e+175],
       [5.68423652e-062, 8.67487299e-067, 1.21018468e+161,
        8.76000979e+169, 1.58663031e-076, 6.46947233e-144],
       [3.59751658e+252, 3.96046095e+246, 1.04918621e-153,
        7.69165785e+218, 5.04621343e+180, 1.04917822e-153],
       [9.08366793e+223, 5.68423652e-062, 8.67487299e-067,
        1.21018468e+161, 8.76000979e+169, 1.04915146e-153],
       [1.94918966e-153, 3.93230450e-062, 9.72390516e-067,
        1.20097858e-071, 2.59027896e-144, 7.79952704e-143]])

In [27]:
np.arange(2,20,4)

array([ 2,  6, 10, 14, 18])

In [28]:
    x= np.linspace(0,10,20)
print(x)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [29]:
a= np.array([4,6,2])
b= np.array([2,7,1])

print(a+b)
print(a*b)
print(b**2)

[ 6 13  3]
[ 8 42  2]
[ 4 49  1]


In [30]:
liste = [1,2,3,4]
array = np.array([5,6,7,8])
print(liste)
print(array)

[1, 2, 3, 4]
[5 6 7 8]


In [31]:
a = np.array([7,2,5])

In [32]:
b=a
c=a

In [33]:
b[1]=7
print(a,b,c)

[7 7 5] [7 7 5] [7 7 5]


In [34]:
a[1]=8
d=a.copy()
print(d)

[7 8 5]


In [35]:
d

array([7, 8, 5])

In [36]:
a

array([7, 8, 5])

In [37]:
a=np.array([3,6,2,8,2,1])
a[0]

3

In [38]:
a[0:6]

array([3, 6, 2, 8, 2, 1])

In [39]:
a[::-1]

array([1, 2, 8, 2, 6, 3])

In [40]:
b = np.array([[10,9,8,7,6],[5,4,3,2,1]])
b

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [41]:
print(b[1,1])

4


In [42]:
print(b[:,3])

[7 2]


In [44]:
print(b[:,2])

[8 3]


In [45]:
b[1,:]

array([5, 4, 3, 2, 1])

In [46]:
b[1,0:5]

array([5, 4, 3, 2, 1])

In [47]:
b[-1,:]

array([5, 4, 3, 2, 1])

In [48]:
b[:,-1]

array([6, 1])

In [49]:
b = b.ravel()
print(b)

[10  9  8  7  6  5  4  3  2  1]


In [50]:
b.T

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])